/**
 * 哔哩哔哩卡片生成器
 */
import { ThemeOptions } from '../types';
import { SvgSanitizerService } from '../utils/svgSanitizer';

/**
 * 生成哔哩哔哩统计卡片
 * @param data 哔哩哔哩用户数据
 * @param theme 主题配置
 * @returns SVG字符串
 */
export const generateBilibiliCard = (data: any, theme: ThemeOptions): string => {
  if (!data) {
    return generateErrorCard('无法获取哔哩哔哩数据', theme);
  }

  if(data instanceof String) {
    return generateErrorCard(data as string, theme);
  }

  const {
    uid,
    username,
    level,
    sign,
    followers,
    following,
    likes,
    views,
    isValid
  } = data;

  // 当前日期
  const currentDate = new Date().toLocaleDateString();

  // 安全处理用户数据
  const safeUsername = SvgSanitizerService.sanitizeUserContent(username || '');
  const safeSign = SvgSanitizerService.sanitizeUserContent(sign || '这个人很懒，什么都没写');
  
  return SvgSanitizerService.sanitize(`<svg xmlns="http://www.w3.org/2000/svg" width="495" height="245" viewBox="0 0 495 245">
    <style>
      .text { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.normal}; fill: ${theme.colors.text.primary}; }
      .header { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.title}; font-weight: bold; fill: ${theme.colors.text.title}; }
      .small { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.small}; fill: ${theme.colors.text.secondary}; }
      .label { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.normal}; fill: ${theme.colors.text.secondary}; }
      .value { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.normal}; font-weight: bold; }
      .footer { font-family: ${theme.fonts.family}; font-size: 10px; fill: ${theme.colors.text.secondary}; }
      .invalid { font-family: ${theme.fonts.family}; font-size: 10px; fill: #dc3545; }
    </style>
    
    <rect width="495" height="245" fill="${theme.colors.background}" rx="${theme.card.borderRadius}" ry="${theme.card.borderRadius}" stroke="${theme.colors.border}" stroke-width="1"/>
    
    <!-- 标题区域 -->
    <text x="25" y="35" class="header">哔哩哔哩统计</text>
    <text x="465" y="35" text-anchor="end" class="small">用户: ${safeUsername}</text>
    
    <!-- 等级和签名 -->
    <g transform="translate(25, 65)">
      <text class="small">Lv.${level}</text>
      <text x="111" class="small" fill="${theme.colors.text.secondary}">${safeSign}</text>
    </g>
    
    <!-- 分隔线 -->
    <rect x="25" y="80" width="445" height="1" fill="${theme.colors.border}"/>
    
    <!-- 统计数据 - 使用网格布局 -->
    <g transform="translate(0, 120)">
      <!-- 第一行 -->
      <g transform="translate(25, 0)">
        <text x="0" class="label">粉丝数:</text>
        <text x="100" class="value" fill="${theme.colors.stats.total}">${SvgSanitizerService.formatNumber(followers)}</text>
      </g>
      
      <g transform="translate(260, 0)">
        <text x="0" class="label">获赞数:</text>
        <text x="100" class="value" fill="${theme.colors.stats.easy}">${SvgSanitizerService.formatNumber(likes)}</text>
      </g>
      
      <!-- 第二行 -->
      <g transform="translate(25, 40)">
        <text x="0" class="label">关注数:</text>
        <text x="100" class="value" fill="${theme.colors.stats.medium}">${SvgSanitizerService.formatNumber(following)}</text>
      </g>
      
      <g transform="translate(260, 40)">
        <text x="0" class="label">播放量:</text>
        <text x="100" class="value" fill="${theme.colors.accent.primary}">${SvgSanitizerService.formatNumber(views)}</text>
      </g>
    </g>
    
    <!-- 分隔线 -->
    <rect x="25" y="200" width="445" height="1" fill="${theme.colors.border}"/>
    
    <!-- 底部信息 -->
    <g transform="translate(0, 225)">
      <text x="25" class="footer">Generated by GitHub Profile Statistics Card</text>
      <text x="465" text-anchor="end" class="footer">更新时间: ${currentDate}</text>
    </g>
  </svg>`);
};

// 导入错误卡片生成器以避免循环依赖
import { generateErrorCard } from './errorCardGenerator';
