/**
 * GitHub卡片生成器
 */
import { ThemeOptions } from '../types';
import { SvgSanitizerService } from '../utils/svgSanitizer';
import { generateErrorCard } from './errorCardGenerator';

/**
 * 生成GitHub访问计数卡片
 * @param count 访问计数
 * @param avatarUrl 头像URL（可选）
 * @param username GitHub用户名（可选）
 * @param theme 主题配置
 * @returns SVG字符串
 */
export const generateGitHubCounterCard = (
  data: any,
  theme: ThemeOptions
): string => {
  // 检查数据是否存在
  if (!data) {
    return generateErrorCard('无法获取GitHub数据', theme);
  }
  
  if(data instanceof String) {
    return generateErrorCard(data as string, theme);
  }

  const {
    count,
    avatarUrl,
    username,
  } = data;

  // 格式化计数
  const formatCount = (num: number): string => {
    if (num >= 1000000) {
      return (num / 1000000).toFixed(1) + 'M';
    } else if (num >= 1000) {
      return (num / 1000).toFixed(1) + 'K';
    }
    return num.toString();
  };

  // 当前日期
  const currentDate = new Date().toLocaleDateString();

  // 安全处理用户数据
  const safeUsername = SvgSanitizerService.sanitizeUserContent(username);

  // 头像部分的SVG
  let avatarSvg = '';
  if (avatarUrl) {
    avatarSvg = `
      <!-- 头像 -->
      <image href="${avatarUrl}" x="25" y="25" width="50" height="50" rx="5" ry="5"/>
    `;
  }

  // 用户名部分的SVG
  const usernameY = avatarUrl ? '105' : '55';

  // 生成渐变ID
  const gradientId = theme.colors.background === '#ffffff' ? 'lightGradient' : 'darkGradient';

  return SvgSanitizerService.sanitize(`<svg xmlns="http://www.w3.org/2000/svg" width="495" height="120" viewBox="0 0 495 120">
    <defs>
      <linearGradient id="${gradientId}" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="${theme.colors.accent.primary}" />
        <stop offset="100%" stop-color="${theme.colors.accent.secondary}" />
      </linearGradient>
    </defs>
    <style>
      .text { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.normal}; fill: ${theme.colors.text.primary}; }
      .header { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.title}; font-weight: bold; fill: ${theme.colors.text.title}; }
      .small { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.small}; fill: ${theme.colors.text.secondary}; }
      .value { font-family: ${theme.fonts.family}; font-size: 36px; font-weight: bold; }
      .footer { font-family: ${theme.fonts.family}; font-size: 10px; fill: ${theme.colors.text.secondary}; }
    </style>
    
    <rect width="495" height="120" fill="${theme.colors.background}" rx="${theme.card.borderRadius}" ry="${theme.card.borderRadius}" stroke="${theme.colors.border}" stroke-width="1"/>
    
    <!-- 左侧头像 -->
    ${avatarSvg}
    
    <!-- 右侧内容 -->
    <g transform="translate(90, 0)">
      <!-- 标题 -->
      <text x="0" y="35" class="header">访问统计</text>
      
      <!-- 用户名 -->
      ${username ? `<text x="0" y="${usernameY}" class="small">@${safeUsername}</text>` : ''}
      
      <!-- 访问计数 -->
      <text x="0" y="90" class="value" fill="url(#${gradientId})")>${formatCount(count)}</text>
    </g>
    
    <!-- 底部信息 -->
    <text x="25" y="110" class="footer">Generated by GitHub Profile Statistics Card</text>
    <text x="465" y="110" text-anchor="end" class="footer">更新于: ${currentDate}</text>
  </svg>`);
};
