/**
 * 掘金卡片生成器
 */
import { JuejinUserData, ThemeOptions } from '../types';
import { SvgSanitizerService } from '../utils/svgSanitizer';

/**
 * 生成掘金统计卡片
 * @param data 掘金用户数据
 * @param theme 主题配置
 * @returns SVG字符串
 */
export const generateJuejinCard = (data: JuejinUserData | string | null, theme: ThemeOptions): string => {
  if (!data) {
    return generateErrorCard('无法获取掘金数据', theme);
  }

  if(data instanceof String) {
    return generateErrorCard(data as string, theme);
  }

  const {
    username,
    desc,
    followers,
    articleCount,
    likes,
    views,
  } = data as JuejinUserData;

  // 当前日期
  const currentDate = new Date().toLocaleDateString();

  // 安全处理用户数据
  const safeUsername = SvgSanitizerService.sanitizeUserContent(username || '');
  const safeDesc = SvgSanitizerService.sanitizeUserContent(desc || '');
  
  return SvgSanitizerService.sanitize(`<svg xmlns="http://www.w3.org/2000/svg" width="495" height="245" viewBox="0 0 495 245">
    <style>
      .text { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.normal}; fill: ${theme.colors.text.primary}; }
      .header { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.title}; font-weight: bold; fill: ${theme.colors.text.title}; }
      .small { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.small}; fill: ${theme.colors.text.secondary}; }
      .label { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.normal}; fill: ${theme.colors.text.secondary}; }
      .value { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.normal}; font-weight: bold; fill: ${theme.colors.text.secondary}; }
      .footer { font-family: ${theme.fonts.family}; font-size: 10px; fill: ${theme.colors.text.secondary}; }
      .power { font-family: ${theme.fonts.family}; font-size: 12px; font-weight: bold; fill: #1E80FF; }
    </style>
    
    <rect width="495" height="245" fill="${theme.colors.background}" rx="${theme.card.borderRadius}" ry="${theme.card.borderRadius}" stroke="${theme.colors.border}" stroke-width="1"/>
    
    <!-- 标题和用户名 -->
    <text x="25" y="35" class="header">掘金统计</text>
    <text x="465" y="35" text-anchor="end" class="small">用户: ${safeUsername}</text>
    
    <!-- 分隔线 -->
    <rect x="25" y="80" width="445" height="1" fill="${theme.colors.border}"/>
    
    <!-- 统计数据 - 左侧 -->
    <text x="25" y="110" class="label">文章数:</text>
    <text x="150" y="110" class="value">${SvgSanitizerService.formatNumber(articleCount)}</text>
    
    <text x="25" y="140" class="label">总浏览量:</text>
    <text x="150" y="140" class="value">${SvgSanitizerService.formatNumber(views)}</text>
    
    <text x="25" y="170" class="label">总点赞数:</text>
    <text x="150" y="170" class="value">${SvgSanitizerService.formatNumber(likes)}</text>
    
    <!-- 统计数据 - 右侧 -->
    <text x="250" y="110" class="label">关注者:</text>
    <text x="375" y="110" class="value">${SvgSanitizerService.formatNumber(followers)}</text>
    
    <text x="250" y="140" class="label">个人简介:</text>
    <text x="375" y="140" class="value">${safeDesc}</text>
    
    <!-- 分隔线 -->
    <rect x="25" y="200" width="445" height="1" fill="${theme.colors.border}"/>
    
    <!-- 底部信息 -->
    <text x="25" y="225" class="footer">Generated by GitHub Profile Statistics Card</text>
    <text x="465" y="225" text-anchor="end" class="footer">更新时间: ${currentDate}</text>
  </svg>`);
};

// 导入错误卡片生成器以避免循环依赖
import { generateErrorCard } from './errorCardGenerator';
