/**
 * LeetCode卡片生成器
 */
import { ILeetCodeUser, ThemeOptions } from '../types';
import { SvgSanitizerService } from '../utils/svgSanitizer';

/**
 * 生成LeetCode统计卡片
 * @param data LeetCode用户数据
 * @param theme 主题配置
 * @returns SVG字符串
 */
export const generateLeetCodeCard = (data: ILeetCodeUser | string, theme: ThemeOptions): string => {
  if (!data || (data instanceof String && data.length === 0)) {
    return generateErrorCard('无法获取LeetCode数据', theme);
  }

  if(data instanceof String) {
    return generateErrorCard(data as string, theme);
  }

  const { username, submitStats, solvedProblem, totalProblem } = data as ILeetCodeUser;
  
  // 提取各难度题目的提交统计数据
  let easySolved = 0;
  let mediumSolved = 0;
  let hardSolved = 0;
  
  if (submitStats && submitStats.acSubmissionNum) {
    submitStats.acSubmissionNum.forEach(item => {
      switch (item.difficulty) {
        case 'EASY':
          easySolved = item.count;
          break;
        case 'MEDIUM':
          mediumSolved = item.count;
          break;
        case 'HARD':
          hardSolved = item.count;
          break;
      }
    });
  }
  
  // 计算百分比
  const totalSolved = solvedProblem || (easySolved + mediumSolved + hardSolved);
  const solvedPercentage = totalProblem ? Math.round((totalSolved / totalProblem) * 100) : 0;
  
  // 当前日期
  const currentDate = new Date().toLocaleDateString();
  
  // 安全处理用户数据
  const safeUsername = SvgSanitizerService.sanitizeUserContent(username);
  
  // 生成SVG内容
  return SvgSanitizerService.sanitize(`<svg xmlns="http://www.w3.org/2000/svg" width="495" height="245" viewBox="0 0 495 245">
    <style>
      .text { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.normal}; fill: ${theme.colors.text.primary}; }
      .header { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.title}; font-weight: bold; fill: ${theme.colors.text.title}; }
      .small { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.small}; fill: ${theme.colors.text.secondary}; }
      .label { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.normal}; fill: ${theme.colors.text.secondary}; }
      .value { font-family: ${theme.fonts.family}; font-size: ${theme.fonts.size.normal}; font-weight: bold; }
      .footer { font-family: ${theme.fonts.family}; font-size: 10px; fill: ${theme.colors.text.secondary}; }
    </style>
    
    <rect width="495" height="245" fill="${theme.colors.background}" rx="${theme.card.borderRadius}" ry="${theme.card.borderRadius}" stroke="${theme.colors.border}" stroke-width="1"/>
    
    <!-- 标题和用户名 -->
    <text x="25" y="35" class="header">LeetCode 统计</text>
    <text x="465" y="35" text-anchor="end" class="small">用户: ${safeUsername}</text>
    
    <!-- 总体进度 -->
    <g transform="translate(25, 70)">
      <text x="0" y="0" class="label">已解决问题:</text>
      <text x="150" y="0" class="value" fill="${theme.colors.stats.total}">${totalSolved} / ${totalProblem}</text>
      <text x="250" y="0" class="value" fill="${theme.colors.stats.total}">${solvedPercentage}%</text>
      
      <!-- 进度条 -->
      <rect x="0" y="15" width="445" height="10" fill="${theme.colors.border}" rx="5" ry="5"/>
      <rect x="0" y="15" width="${(solvedPercentage / 100) * 445}" height="10" fill="${theme.colors.stats.total}" rx="5" ry="5"/>
    </g>
    
    <!-- 分隔线 -->
    <rect x="25" y="105" width="445" height="1" fill="${theme.colors.border}"/>
    
    <!-- 各难度统计 -->
    <g transform="translate(25, 140)">
      <!-- 简单题目 -->
      <g>
        <text x="0" y="0" class="label">简单:</text>
        <text x="100" y="0" class="value" fill="${theme.colors.stats.easy}">${easySolved}</text>
        <circle cx="50" cy="0" r="5" fill="${theme.colors.stats.easy}"/>
      </g>
      
      <!-- 中等题目 -->
      <g transform="translate(150, 0)">
        <text x="0" y="0" class="label">中等:</text>
        <text x="100" y="0" class="value" fill="${theme.colors.stats.medium}">${mediumSolved}</text>
        <circle cx="50" cy="0" r="5" fill="${theme.colors.stats.medium}"/>
      </g>
      
      <!-- 困难题目 -->
      <g transform="translate(300, 0)">
        <text x="0" y="0" class="label">困难:</text>
        <text x="100" y="0" class="value" fill="${theme.colors.stats.hard}">${hardSolved}</text>
        <circle cx="50" cy="0" r="5" fill="${theme.colors.stats.hard}"/>
      </g>
    </g>
    
    <!-- 分隔线 -->
    <rect x="25" y="175" width="445" height="1" fill="${theme.colors.border}"/>
    
    <!-- 底部信息 -->
    <text x="25" y="205" class="footer">Generated by GitHub Profile Statistics Card</text>
    <text x="465" y="205" text-anchor="end" class="footer">更新于: ${currentDate}</text>
  </svg>`);
};

// 导入错误卡片生成器以避免循环依赖
import { generateErrorCard } from './errorCardGenerator';
